(()=>{
  const apply=()=>{
    const timeline=document.querySelector('.timeline');
    if(!timeline)return;
    const day=[...timeline.querySelectorAll(':scope > article.day')].find(a=>a.querySelector('time')?.textContent.trim()==='14 OUT');
    if(!day)return;
    const details=day.querySelector('details');
    const summary=details?.querySelector('.summary-text');
    const content=details?.querySelector('.day-content');
    if(summary)summary.innerHTML='<span>ITÁLIA · VERONA + SIRMIONE + LAGO DI GARDA</span><h3>Verona + Sirmione</h3><small>Arena · Julieta · Ponte Pietra · Castello Scaligero · Jamaica Beach · pôr do sol</small>';
    if(content)content.innerHTML=`
      <div class="day4-hero day14-verona"><img src="https://commons.wikimedia.org/wiki/Special:FilePath/Verona%20-%20Piazza%20Bra%20-%20Arena.jpg?width=1600" alt="Arena de Verona" loading="lazy"><div class="day4-hero-copy"><span>14 OUT · VERONA + SIRMIONE</span><h3>Verona pela manhã, Garda à tarde</h3><p>Centro histórico de Verona sem correria, seguido por Sirmione, Jamaica Beach e pôr do sol no Lago di Garda.</p></div></div>
      <div class="day4-grid">
        <section><b>🚗 08:00 · Estacionar em Verona</b><p><strong>Parcheggio Porta Palio</strong> · boa base para fazer todo o centro histórico a pé.</p><a class="day4-map" href="https://www.google.com/maps/search/?api=1&query=Parcheggio+Porta+Palio+Verona" target="_blank" rel="noopener noreferrer">📍 Porta Palio</a></section>
        <section class="day11-hike"><b>🏟️ 08:30 · Piazza Bra + Arena di Verona</b><p>Começar pelo principal cartão-postal da cidade.</p><small>⭐ Prioridade: parte externa da Arena, economizando tempo para o restante da manhã.</small><a class="day4-map" href="https://www.google.com/maps/search/?api=1&query=Arena+di+Verona" target="_blank" rel="noopener noreferrer">📍 Arena di Verona</a></section>
        <section><b>🚶 09:00 · Via Mazzini</b><p>Rua de pedestres que liga a Arena ao coração histórico de Verona.</p><a class="day4-map" href="https://www.google.com/maps/search/?api=1&query=Via+Mazzini+Verona" target="_blank" rel="noopener noreferrer">📍 Via Mazzini</a></section>
        <section><b>❤️ 09:20 · Casa de Julieta</b><p>Visitar o famoso pátio e ver a varanda.</p><small>💡 Não entrar no museu neste dia.</small><a class="day4-map" href="https://www.google.com/maps/search/?api=1&query=Casa+di+Giulietta+Verona" target="_blank" rel="noopener noreferrer">📍 Casa di Giulietta</a></section>
        <section class="day4-food"><b>🏛️☕ 09:45 · Piazza delle Erbe</b><p>Uma das praças mais bonitas de Verona, cercada por prédios históricos e fachadas coloridas.</p><small>☕ Aproveitar para café + cornetto.</small><a class="day4-map" href="https://www.google.com/maps/search/?api=1&query=Piazza+delle+Erbe+Verona" target="_blank" rel="noopener noreferrer">📍 Piazza delle Erbe</a></section>
        <section><b>🏛️ 10:15 · Piazza dei Signori + Arche Scaligere</b><p>Dois pontos históricos praticamente lado a lado.</p><div class="day4-links"><a href="https://www.google.com/maps/search/?api=1&query=Piazza+dei+Signori+Verona" target="_blank" rel="noopener noreferrer">Piazza dei Signori</a><a href="https://www.google.com/maps/search/?api=1&query=Arche+Scaligere+Verona" target="_blank" rel="noopener noreferrer">Arche Scaligere</a></div></section>
        <section><b>🌉 10:40 · Ponte Pietra</b><p>Um dos cenários mais bonitos da cidade, com o rio Adige e as colinas ao fundo.</p><a class="day4-map" href="https://www.google.com/maps/search/?api=1&query=Ponte+Pietra+Verona" target="_blank" rel="noopener noreferrer">📍 Ponte Pietra</a></section>
        <section><b>🚶 11:00–11:45 · Retorno ao carro</b><p>Voltar tranquilamente pelo centro.</p><small>Se estiverem dentro do horário, passar por <strong>Porta Borsari</strong> e <strong>Castelvecchio</strong>.</small><div class="day4-links"><a href="https://www.google.com/maps/search/?api=1&query=Porta+Borsari+Verona" target="_blank" rel="noopener noreferrer">Porta Borsari</a><a href="https://www.google.com/maps/search/?api=1&query=Castelvecchio+Verona" target="_blank" rel="noopener noreferrer">Castelvecchio</a></div></section>
        <section class="day4-flight"><b>🚗 11:45–12:45 · Verona → Sirmione</b><p>Reservar cerca de 1 hora contando trânsito e estacionamento.</p><a class="day4-map" href="https://www.google.com/maps/dir/?api=1&origin=Verona%2C+Italy&destination=Sirmione%2C+Italy" target="_blank" rel="noopener noreferrer">🧭 Abrir rota</a></section>
        <section><b>🚗 12:45 · Estacionamento em Sirmione</b><p><strong>Parcheggio Monte Baldo</strong> · bem localizado para entrar caminhando na península.</p><a class="day4-map" href="https://www.google.com/maps/search/?api=1&query=Parcheggio+Monte+Baldo+Sirmione" target="_blank" rel="noopener noreferrer">🅿️ Monte Baldo</a></section>
        <section class="day4-food"><b>🍕 13:00–14:00 · Almoço</b><p>Almoço já em Sirmione.</p><small>Pizza, massa ou panino · manter a parada simples e sem alongar demais.</small></section>
        <section class="day11-return"><b>🏰 14:00 · Castello Scaligero</b><p>Castelo medieval cercado pelas águas do Garda, o grande cartão-postal de Sirmione.</p><small>➡️ Priorizar exterior + fotos em vez da visita completa.</small><a class="day4-map" href="https://www.google.com/maps/search/?api=1&query=Castello+Scaligero+Sirmione" target="_blank" rel="noopener noreferrer">📍 Castello Scaligero</a></section>
        <section><b>🏘️ 14:30 · Centro histórico</b><p>Vielas, pequenas praças, casas antigas e vistas do lago.</p><small>🍦 Hora perfeita para um gelato italiano.</small><a class="day4-map" href="https://www.google.com/maps/search/?api=1&query=Centro+Storico+Sirmione" target="_blank" rel="noopener noreferrer">📍 Centro storico</a></section>
        <section><b>🌊 15:15 · Caminhada pela península</b><p>Seguir em direção ao extremo norte, aproveitando os acessos ao Lago di Garda pelo caminho.</p></section>
        <section class="day11-hike"><b>🏖️ 15:45–16:45 · Jamaica Beach</b><p>Grandes placas de pedra junto à água e uma das paisagens mais diferentes do Garda.</p><small>📸 Mesmo sem entrar no lago em outubro, vale muito pelas fotos e pela paisagem.</small><a class="day4-map" href="https://www.google.com/maps/search/?api=1&query=Jamaica+Beach+Sirmione" target="_blank" rel="noopener noreferrer">📍 Jamaica Beach</a></section>
        <section class="day14-free"><b>⭐ 16:45–17:30 · Tempo livre</b><p>Caminhar sem pressa, tomar alguma coisa, parar para fotos ou simplesmente ficar à beira do Garda.</p><small><strong>Grotte di Catullo</strong> ficam fora da programação principal. Só considerar se estiverem adiantados e realmente quiserem visitar.</small></section>
        <section class="day4-flight day14-sunset"><b>🌅 17:30–18:30 · Pôr do sol no Lago di Garda</b><p>Começar a retornar lentamente pela península pelo lado oeste.</p><small>Sem atração obrigatória: escolher um lugar bonito e assistir ao sol baixar sobre o Garda.</small><div class="day4-links"><a href="https://www.google.com/maps/search/?api=1&query=Passeggiata+delle+Muse+Sirmione" target="_blank" rel="noopener noreferrer">Passeggiata delle Muse</a><a href="https://www.google.com/maps/search/?api=1&query=Spiaggia+del+Prete+Sirmione" target="_blank" rel="noopener noreferrer">Spiaggia del Prete</a></div></section>
        <section class="day4-food"><b>🍝 18:45–19:45 · Jantar em Sirmione</b><p>Voltar ao centro histórico e procurar uma trattoria ou pizzeria simples.</p><small>Boa forma de fechar o dia sem transformar o jantar em uma parada longa.</small></section>
        <section class="day4-flight day14-night"><b>🚗 20:00 · Sirmione → Medole</b><p>Saída depois do jantar · chegada prevista em Medole por volta de <strong>20:45–21:00</strong>.</p><a class="day4-map" href="https://www.google.com/maps/dir/?api=1&origin=Sirmione%2C+Italy&destination=Medole%2C+Italy" target="_blank" rel="noopener noreferrer">🧭 Abrir rota</a></section>
        <section class="day14-summary"><b>🗺️ Resumo do dia</b><p><strong>08:00 Verona</strong> → Arena → Casa de Julieta → Piazza delle Erbe → Piazza dei Signori → Ponte Pietra → <strong>11:45 saída</strong> → <strong>12:45 Sirmione</strong> → almoço → Castello Scaligero → centro histórico → Jamaica Beach → tempo livre → 🌅 pôr do sol no Garda → jantar → <strong>20:00 Medole</strong>.</p></section>
      </div>`;
    if(!document.getElementById('day14-style')){const s=document.createElement('style');s.id='day14-style';s.textContent='.day14-verona:after{background:linear-gradient(90deg,rgba(49,32,24,.88),rgba(49,32,24,.08))}.day14-sunset{background:#f5efe3!important}.day14-night{background:#f1f3ed!important}.day14-free{background:#f7f3e9!important}.day14-summary{background:#eef4f0!important;border-left:3px solid #1e5a47}';document.head.appendChild(s);}
  };
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(apply,350));else setTimeout(apply,350);
})();