(()=>{
 const run=()=>{
  const timeline=document.querySelector('.timeline'); if(!timeline)return;
  const day=[...timeline.querySelectorAll(':scope > article.day')].find(a=>a.querySelector('time')?.textContent.trim()==='14 OUT'); if(!day)return;
  const s=day.querySelector('.summary-text'),c=day.querySelector('.day-content');
  if(s)s.innerHTML='<span>ITÁLIA · VERONA + SIRMIONE</span><h3>Verona + Sirmione</h3><small>Arena · Julieta · Piazza delle Erbe · Ponte Pietra · Castello Scaligero · Jamaica Beach</small>';
  if(c)c.innerHTML=`<div class="day4-hero"><img src="https://commons.wikimedia.org/wiki/Special:FilePath/Verona%20-%20Piazza%20Bra%20-%20Arena.jpg?width=1600" alt="Arena de Verona e Piazza Bra" loading="lazy"><div class="day4-hero-copy"><span>14 OUT · VERONA + SIRMIONE</span><h3>História pela manhã, Lago di Garda à tarde</h3><p>Os grandes cartões-postais de Verona em um roteiro a pé e uma tarde mais contemplativa em Sirmione, terminando com o pôr do sol no Garda.</p></div></div><div class="day4-grid">
<section><b>🚗 07:45–08:30 · Chegada a Verona</b><p>Chegar cedo e deixar o carro fora do centro histórico. Fazer todo o roteiro central a pé.</p><small>🅿️ Reservar aproximadamente €8–12 para a manhã.</small><a class="day4-map" href="https://www.google.com/maps/search/?api=1&query=Parcheggio+Tribunale+Verona" target="_blank" rel="noopener noreferrer">📍 Parcheggio Tribunale</a></section>
<section><b>🏛️ 08:45–09:10 · Piazza Bra</b><p>Primeiro contato com Verona: jardins, Palazzo Barbieri e a fachada monumental da Arena.</p><small>📸 Excelente horário para fotografar antes do maior movimento.</small><a class="day4-map" href="https://www.google.com/maps/search/?api=1&query=Piazza+Bra+Verona" target="_blank" rel="noopener noreferrer">📍 Piazza Bra</a></section>
<section class="day11-hike"><b>🏟️ 09:10–09:55 · Arena di Verona ⭐⭐⭐</b><p>Visita curta ao anfiteatro romano, incluindo arquibancadas e vistas internas. Se houver atraso, o exterior já entrega boa parte da experiência.</p><img src="https://commons.wikimedia.org/wiki/Special:FilePath/Verona%20-%20Piazza%20Bra%20-%20Arena.jpg?width=1400" alt="Arena di Verona" style="width:100%;border-radius:14px;margin-top:12px;max-height:340px;object-fit:cover" loading="lazy"><a class="day4-map" href="https://www.google.com/maps/search/?api=1&query=Arena+di+Verona" target="_blank" rel="noopener noreferrer">📍 Arena di Verona</a></section>
<section><b>🚶 09:55–10:15 · Via Mazzini</b><p>Caminhada pela principal rua de pedestres, ligando Piazza Bra ao coração medieval.</p><small>☕ Boa oportunidade para um espresso rápido · ~€1,50–2,50.</small><a class="day4-map" href="https://www.google.com/maps/search/?api=1&query=Via+Mazzini+Verona" target="_blank" rel="noopener noreferrer">📍 Via Mazzini</a></section>
<section><b>❤️ 10:15–10:45 · Casa de Julieta</b><p>Priorizar o pátio, a famosa varanda e a atmosfera do local, sem alongar a visita ao museu.</p><small>💶 Pátio: cerca de €5 · reserva antecipada recomendada.</small><a class="day4-map" href="https://www.google.com/maps/search/?api=1&query=Casa+di+Giulietta+Verona" target="_blank" rel="noopener noreferrer">📍 Casa di Giulietta</a></section>
<section class="day11-hike"><b>🏘️ 10:50–11:20 · Piazza delle Erbe ⭐⭐⭐</b><p>Uma das praças mais bonitas de Verona: fachadas históricas, mercado, Palazzo Maffei, Madonna Verona e Torre dei Lamberti.</p><img src="https://commons.wikimedia.org/wiki/Special:FilePath/Piazza%20delle%20Erbe%20Verona.jpg?width=1400" alt="Piazza delle Erbe em Verona" style="width:100%;border-radius:14px;margin-top:12px;max-height:340px;object-fit:cover" loading="lazy"><a class="day4-map" href="https://www.google.com/maps/search/?api=1&query=Piazza+delle+Erbe+Verona" target="_blank" rel="noopener noreferrer">📍 Piazza delle Erbe</a></section>
<section><b>🏛️ 11:20–11:40 · Piazza dei Signori + Arche Scaligere</b><p>Passagem pelo elegante conjunto medieval e pelos túmulos monumentais da família Scaligeri.</p><div class="day4-links"><a href="https://www.google.com/maps/search/?api=1&query=Piazza+dei+Signori+Verona" target="_blank" rel="noopener noreferrer">📍 Piazza dei Signori</a><a href="https://www.google.com/maps/search/?api=1&query=Arche+Scaligere+Verona" target="_blank" rel="noopener noreferrer">📍 Arche Scaligere</a></div></section>
<section class="day11-hike"><b>🌉 11:40–12:10 · Ponte Pietra ⭐⭐⭐</b><p>Um dos cenários mais fotogênicos de Verona, com o rio Adige, as colinas e Castel San Pietro ao fundo.</p><small>💡 Não subir ao Castel San Pietro neste dia: preserve tempo para Sirmione.</small><img src="https://commons.wikimedia.org/wiki/Special:FilePath/Ponte%20Pietra%20Verona.jpg?width=1400" alt="Ponte Pietra em Verona" style="width:100%;border-radius:14px;margin-top:12px;max-height:340px;object-fit:cover" loading="lazy"><a class="day4-map" href="https://www.google.com/maps/search/?api=1&query=Ponte+Pietra+Verona" target="_blank" rel="noopener noreferrer">📍 Ponte Pietra</a></section>
<section class="day4-food"><b>🍝 12:15–13:00 · Almoço em Verona</b><p>Almoço leve e relativamente rápido. Boas escolhas: <strong>bigoli, pizza, panini com salumi</strong> ou um prato regional.</p><small>💶 ~€15–25 por pessoa. Evitar uma refeição longa para proteger a tarde no lago.</small></section>
<section class="day4-flight"><b>🚗 13:20–14:20 · Verona → Sirmione</b><p>Reservar cerca de 50–60 min, já considerando a aproximação da península e estacionamento.</p><small>⚠️ Não entrar de carro no centro histórico de Sirmione.</small><div class="day4-links"><a href="https://www.google.com/maps/dir/?api=1&origin=Verona%2C+Italy&destination=Sirmione%2C+Italy" target="_blank" rel="noopener noreferrer">🧭 Abrir rota</a><a href="https://www.google.com/maps/search/?api=1&query=Parking+Piazza+Mercato+Sirmione" target="_blank" rel="noopener noreferrer">🅿️ Piazza Mercato</a></div></section>
<section class="day11-hike"><b>🏰 14:30–15:10 · Castello Scaligero ⭐⭐⭐</b><p>O grande cartão-postal de Sirmione: fortaleza medieval cercada pelas águas do Lago di Garda. Priorizar a subida e as vistas sobre os telhados, marina e lago.</p><img src="https://commons.wikimedia.org/wiki/Special:FilePath/Castello%20Scaligero%20di%20Sirmione.jpg?width=1400" alt="Castello Scaligero em Sirmione" style="width:100%;border-radius:14px;margin-top:12px;max-height:340px;object-fit:cover" loading="lazy"><a class="day4-map" href="https://www.google.com/maps/search/?api=1&query=Castello+Scaligero+Sirmione" target="_blank" rel="noopener noreferrer">📍 Castello Scaligero</a></section>
<section><b>🍦 15:10–15:30 · Centro histórico + gelato</b><p>Diminuir o ritmo e passear pelas vielas, pequenas praças e fachadas da península.</p><small>🍦 Gelato ~€3–5 · primeira pausa tranquila da tarde.</small><a class="day4-map" href="https://www.google.com/maps/search/?api=1&query=Centro+Storico+Sirmione" target="_blank" rel="noopener noreferrer">📍 Centro storico</a></section>
<section><b>🌿 15:30–16:00 · Caminhada pela península</b><p>Via Vittorio Emanuele → Via Giuseppe Piana → extremo norte, aproveitando os acessos e vistas do Garda.</p></section>
<section><b>🏛️ 16:00–16:50 · Grotte di Catullo</b><p>Ruínas de uma grande villa romana em meio a oliveiras e vistas abertas do lago.</p><small>🔄 Opcional: só fazer se a última entrada de outubro permitir uma visita confortável. Caso contrário, seguir direto para Jamaica Beach.</small><a class="day4-map" href="https://www.google.com/maps/search/?api=1&query=Grotte+di+Catullo+Sirmione" target="_blank" rel="noopener noreferrer">📍 Grotte di Catullo</a></section>
<section class="day11-hike"><b>🏖️ 16:50–17:25 · Jamaica Beach ⭐⭐⭐</b><p>Grandes placas de pedra junto à água e uma das paisagens mais diferentes de Sirmione. Em outubro, vale principalmente pelo cenário e pelas fotos.</p><small>🪑 Reservar alguns minutos simplesmente para sentar e descansar à beira do lago.</small><img src="https://commons.wikimedia.org/wiki/Special:FilePath/Jamaica%20Beach%20Sirmione.jpg?width=1400" alt="Jamaica Beach em Sirmione" style="width:100%;border-radius:14px;margin-top:12px;max-height:340px;object-fit:cover" loading="lazy"><a class="day4-map" href="https://www.google.com/maps/search/?api=1&query=Jamaica+Beach+Sirmione" target="_blank" rel="noopener noreferrer">📍 Jamaica Beach</a></section>
<section class="day4-flight"><b>🌅 17:25–18:35 · Caminhada + pôr do sol ⭐⭐⭐</b><p>Retornar lentamente pela margem, sem novas atrações obrigatórias. Aproveitar a luz dourada sobre o Garda e escolher espontaneamente o melhor ponto para parar.</p><small>🌅 Pôr do sol esperado por volta de 18:34.</small><div class="day4-links"><a href="https://www.google.com/maps/search/?api=1&query=Passeggiata+delle+Muse+Sirmione" target="_blank" rel="noopener noreferrer">📍 Passeggiata delle Muse</a><a href="https://www.google.com/maps/search/?api=1&query=Spiaggia+del+Prete+Sirmione" target="_blank" rel="noopener noreferrer">📍 Spiaggia del Prete</a></div></section>
<section><b>🍹 18:35–19:10 · Aperitivo + descanso</b><p>Sentar em um café ou bar depois do pôr do sol. Pausa importante após um dia com bastante caminhada.</p><small>💶 Spritz ~€5–8 · café ~€1,50–2,50.</small></section>
<section class="day4-food"><b>🍕 19:15–20:30 · Jantar em Sirmione</b><p>Fechar o dia com pizza, massa ou cozinha regional em uma trattoria do centro histórico.</p><small>💶 ~€20–35 por pessoa.</small></section>
<section class="day4-flight"><b>🚗 20:30 · Retorno</b><p>Voltar ao estacionamento e seguir para a hospedagem. Não acrescentar Desenzano, Peschiera ou outra cidade: o dia já estará completo.</p></section>
<section><b>💶 Custos aproximados</b><p><strong>Por pessoa:</strong> Arena ~€10–12 · pátio de Julieta ~€5 · almoço €15–25 · Castello ~€8 · Grotte ~€10 · gelato €3–5 · aperitivo €5–8 · jantar €20–35.</p><small>Estimativa geral: <strong>€75–110 por pessoa</strong>, sem combustível/pedágio.</small></section>
<section><b>🔄 Plano B se houver atraso</b><p>Não tentem recuperar o tempo correndo. Cortar nesta ordem: <strong>Grotte di Catullo → interior da Arena → qualquer visita interna adicional em Verona</strong>.</p><small>⭐ Preservar Piazza delle Erbe, Ponte Pietra, Castello Scaligero e o fim de tarde em Sirmione.</small></section>
<section><b>🗺️ Resumo</b><p><strong>08:45</strong> Verona → Piazza Bra → Arena → Julieta → Piazza delle Erbe → Signori → Ponte Pietra → almoço → <strong>13:20</strong> Sirmione → Castello → centro → Grotte (opcional) → Jamaica Beach → <strong>18:34 pôr do sol</strong> → aperitivo → jantar → <strong>20:30 retorno</strong>.</p><small>🟢 Ritmo 7/10 · completo, mas com a tarde progressivamente mais tranquila.</small></section>
</div>`;
 };
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(run,550));else setTimeout(run,550);
})();