(()=>{
 const run=()=>{
  const timeline=document.querySelector('.timeline'); if(!timeline)return;
  const day=[...timeline.querySelectorAll(':scope > article.day')].find(a=>a.querySelector('time')?.textContent.trim()==='04 OUT');
  const s=day?.querySelector('.summary-text'),c=day?.querySelector('.day-content'); if(!s||!c)return;
  s.innerHTML='<span>PORTUGAL · BELÉM</span><h3>Jerónimos + Descobrimentos + Torre + MAAT</h3><small>Pastéis de Belém · Jerónimos · Tejo · Torre de Belém · MAAT · voo 21:30</small>';
  c.innerHTML=`<div class="day4-hero"><img src="https://images.unsplash.com/photo-1555881400-74d7acaacd8b?auto=format&fit=crop&w=1800&q=88" alt="Lisboa e Belém" loading="lazy"><div class="day4-hero-copy"><span>04 OUT · BELÉM</span><h3>Belém com calma antes do voo</h3><p>Os grandes clássicos de Belém, caminhada pelo Tejo, pausas bem distribuídas e margem confortável para o voo a Atenas às 21:30.</p></div></div><div class="day4-grid">
<section><b>🚗 07:45–08:30 · Loures → Belém</b><p>Sair cedo da hospedagem e seguir diretamente para Belém. Para o grupo, Uber/Bolt pode ser a opção mais prática.</p><small>🧳 Deixar as malas na hospedagem e levar apenas mochila pequena.</small><a class="day4-map" href="https://maps.google.com/?q=Pasteis+de+Belem+Lisboa" target="_blank" rel="noopener noreferrer">📍 Começar em Belém</a></section>
<section class="day4-food"><b>🥧 08:30–09:10 · Pastéis de Belém</b><p>Café da manhã com o famoso pastel servido quentinho. Vale entrar nas salas internas revestidas de azulejos.</p><small>💶 ~€3–6 por pessoa.</small><img src="https://commons.wikimedia.org/wiki/Special:FilePath/Past%C3%A9is%20de%20Bel%C3%A9m.JPG?width=1400" alt="Pastéis de Belém" style="width:100%;border-radius:14px;margin-top:12px;max-height:340px;object-fit:cover" loading="lazy"><div class="day4-links"><a href="https://maps.google.com/?q=Pasteis+de+Belem+Rua+de+Belem+84" target="_blank" rel="noopener noreferrer">📍 Localização</a><a href="https://pasteisdebelem.pt/" target="_blank" rel="noopener noreferrer">🌐 Site oficial</a></div></section>
<section class="day11-hike"><b>⛪ 09:15–10:40 · Mosteiro dos Jerónimos ⭐⭐⭐</b><p>Chegar antes da abertura para fotografar a fachada e visitar o claustro a partir das 09:30.</p><small>💶 Ingresso ~€18 · ⭐ prioridade nº 1 do dia. Aos domingos, deixar a igreja para depois das 14:00.</small><img src="https://commons.wikimedia.org/wiki/Special:FilePath/Mosteiro%20dos%20Jer%C3%B3nimos%20-%20Lisboa.jpg?width=1400" alt="Mosteiro dos Jerónimos" style="width:100%;border-radius:14px;margin-top:12px;max-height:340px;object-fit:cover" loading="lazy"><div class="day4-links"><a href="https://maps.google.com/?q=Mosteiro+dos+Jeronimos+Lisboa" target="_blank" rel="noopener noreferrer">📍 Jerónimos</a><a href="https://mosteirojeronimos.torrebelem.gov.pt/" target="_blank" rel="noopener noreferrer">🎟️ Site oficial</a></div></section>
<section><b>🌳 10:45–11:05 · Praça do Império</b><p>Travessia tranquila pelos jardins, com ótima vista frontal do Mosteiro e tempo para fotos.</p><small>⏱️ Pausa leve antes de seguir para a margem do Tejo.</small></section>
<section class="day11-hike"><b>⚓ 11:10–11:50 · Padrão dos Descobrimentos</b><p>Ver a Rosa dos Ventos e, se a fila estiver curta, subir ao miradouro para a vista do Tejo, Jerónimos e Ponte 25 de Abril.</p><small>💶 ~€5–10 · se houver fila grande, contemplar apenas externamente.</small><img src="https://commons.wikimedia.org/wiki/Special:FilePath/Padrao%20dos%20Descobrimentos%20Lisboa.jpg?width=1400" alt="Padrão dos Descobrimentos" style="width:100%;border-radius:14px;margin-top:12px;max-height:340px;object-fit:cover" loading="lazy"><a class="day4-map" href="https://maps.google.com/?q=Padrao+dos+Descobrimentos+Lisboa" target="_blank" rel="noopener noreferrer">📍 Padrão</a></section>
<section><b>🌊 11:50–12:25 · Caminhada pelo Tejo</b><p>Padrão → Fundação Champalimaud → Torre de Belém. Trecho plano, agradável e ótimo para fotos.</p><small>🚶 ~15–20 min de caminhada efetiva; reservar cerca de 30 min com paradas.</small></section>
<section class="day11-hike"><b>🏰 12:25–12:55 · Torre de Belém ⭐⭐⭐</b><p>Visita externa ao grande símbolo de Lisboa. Aproveitar o Jardim da Torre e fotografar de diferentes ângulos.</p><small>💶 Grátis na visita externa · verificar perto da viagem se o interior já reabriu após as obras.</small><img src="https://commons.wikimedia.org/wiki/Special:FilePath/Torre%20de%20Bel%C3%A9m%20-%20Lisboa%20Portugal.jpg?width=1400" alt="Torre de Belém" style="width:100%;border-radius:14px;margin-top:12px;max-height:340px;object-fit:cover" loading="lazy"><a class="day4-map" href="https://maps.google.com/?q=Torre+de+Belem+Lisboa" target="_blank" rel="noopener noreferrer">📍 Torre de Belém</a></section>
<section class="day4-food"><b>🍽️ 13:00–14:00 · Almoço</b><p>Opção econômica: <strong>Pão Pão Queijo Queijo</strong>. Para comida portuguesa mais tradicional, alternativa: <strong>Adega de Belém</strong>.</p><small>💶 Econômico ~€8–15 por pessoa; tradicional ~€15–35.</small><div class="day4-links"><a href="https://maps.google.com/?q=Pao+Pao+Queijo+Queijo+Belem+Lisboa" target="_blank" rel="noopener noreferrer">📍 Econômico</a><a href="https://maps.google.com/?q=Adega+de+Belem+Lisboa" target="_blank" rel="noopener noreferrer">📍 Tradicional</a></div></section>
<section><b>⛪ 14:05–14:25 · Igreja de Santa Maria de Belém</b><p>Retorno rápido aos Jerónimos para conhecer a igreja, que aos domingos abre à tarde, e ver os túmulos associados a Vasco da Gama e Luís de Camões.</p><small>⏱️ Cerca de 20 min são suficientes.</small><a class="day4-map" href="https://maps.google.com/?q=Igreja+Santa+Maria+de+Belem+Jeronimos" target="_blank" rel="noopener noreferrer">📍 Igreja</a></section>
<section><b>🌳 14:30–15:00 · Descanso</b><p>Meia hora sem atração: sentar no jardim, tomar água ou café e descansar antes da parte final.</p><small>❤️ Pausa proposital para manter o dia leve antes do aeroporto.</small></section>
<section class="day11-hike"><b>🏛️ 15:10–15:50 · MAAT + cobertura</b><p>Não é necessário entrar no museu: aproveitar a arquitetura contemporânea, a cobertura e a margem do Tejo com vista para a Ponte 25 de Abril.</p><small>💶 Área externa grátis.</small><img src="https://commons.wikimedia.org/wiki/Special:FilePath/MAAT%20Lisbon.jpg?width=1400" alt="MAAT em Lisboa" style="width:100%;border-radius:14px;margin-top:12px;max-height:340px;object-fit:cover" loading="lazy"><a class="day4-map" href="https://maps.google.com/?q=MAAT+Lisboa" target="_blank" rel="noopener noreferrer">📍 MAAT</a></section>
<section><b>💎 15:50–16:15 · Central Tejo e orla</b><p>Trecho menos turístico ao redor do MAAT e da antiga Central Tejo. Caminhar sem pressa e curtir os últimos momentos junto ao rio.</p><small>📸 Bom contraponto à parte monumental de Belém.</small></section>
<section class="day4-food"><b>☕ 16:15–16:40 · Última pausa</b><p>Café, água ou sorvete. <strong>16:40 é o limite para encerrar o turismo.</strong></p><small>Depois disso, prioridade total para malas e aeroporto.</small></section>
<section class="day4-flight"><b>✈️ 16:40–21:30 · Belém → hospedagem → aeroporto</b><p><strong>16:40</strong> chamar Uber/Bolt → <strong>17:15–17:45</strong> pegar malas → <strong>17:45–18:00</strong> sair para o aeroporto → chegada planejada <strong>18:30–19:00</strong>.</p><small>✈️ Voo Lisboa → Atenas às <strong>21:30</strong>. A margem foi deixada propositalmente confortável.</small><a class="day4-map" href="https://maps.google.com/?q=Aeroporto+Humberto+Delgado+Lisboa" target="_blank" rel="noopener noreferrer">📍 Aeroporto de Lisboa</a></section>
<section><b>💶 Custos estimados</b><p>Pastéis €3–6 · Jerónimos ~€18 · Padrão ~€5–10 · almoço €8–15 · café/água €3–5 · transporte dividido ~€8–15.</p><small>💰 Total aproximado: <strong>€45–70 por pessoa</strong>, podendo cair ao pular o miradouro do Padrão.</small></section>
<section><b>🌧️ Plano B</b><p>Se chover, reduzir a caminhada pela orla e considerar o <strong>Museu de Marinha</strong>, junto aos Jerónimos.</p><small>Não acrescentaria centro de Lisboa ou LX Factory neste dia: Belém já entrega um passeio completo sem colocar o voo em risco.</small><a class="day4-map" href="https://maps.google.com/?q=Museu+de+Marinha+Lisboa" target="_blank" rel="noopener noreferrer">📍 Museu de Marinha</a></section>
<section><b>🗺️ Resumo</b><p><strong>08:30</strong> Pastéis → <strong>09:30</strong> Jerónimos → Padrão → Tejo → Torre → almoço → igreja → descanso → MAAT → <strong>16:40</strong> saída → <strong>21:30</strong> voo.</p><small>🟢 Ritmo 6/10 · bastante completo, mas equilibrado e com boa margem para o aeroporto.</small></section>
</div>`;
 };
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(run,700));else setTimeout(run,700);
})();