(()=>{
 const run=()=>{
  const timeline=document.querySelector('.timeline'); if(!timeline)return;
  const day=[...timeline.querySelectorAll(':scope > article.day')].find(a=>a.querySelector('time')?.textContent.trim()==='13 OUT');
  const s=day?.querySelector('.summary-text'),c=day?.querySelector('.day-content'); if(!s||!c)return;
  s.innerHTML='<span>ITÁLIA · VENEZA</span><h3>Rialto + San Marco + Dorsoduro</h3><small>Rialto · Basílica · Palazzo Ducale · Castello · Accademia · Grande Canal</small>';
  c.innerHTML=`<div class="day4-hero"><img src="https://images.unsplash.com/photo-1523906834658-6e24ef2386f9?auto=format&fit=crop&w=1800&q=88" alt="Grande Canal em Veneza" loading="lazy"><div class="day4-hero-copy"><span>13 OUT · VENEZA</span><h3>Veneza dos clássicos aos canais tranquilos</h3><p>Rialto e San Marco pela manhã, bairros charmosos à tarde e Grande Canal no entardecer.</p></div></div><div class="day4-grid">
<section><b>🚗 07:00 · Treviso → Mestre</b><p>Ir de carro até <strong>Venezia Mestre</strong>, estacionar próximo à estação e seguir de trem até Venezia Santa Lucia.</p><small>⏱️ Treviso → Mestre: ~35–45 min · trem Mestre → Santa Lucia: ~10–12 min.</small><div class="day4-links"><a href="https://maps.google.com/?q=Venezia+Mestre+FS" target="_blank" rel="noopener noreferrer">📍 Mestre</a><a href="https://maps.google.com/?q=Venezia+Santa+Lucia" target="_blank" rel="noopener noreferrer">📍 Santa Lucia</a></div></section>
<section><b>🌊 08:10 · Chegada a Santa Lucia</b><p>Primeiro contato com o <strong>Grande Canal</strong> logo na saída da estação.</p><small>Não pegar vaporetto agora: a ideia é entrar em Veneza caminhando.</small></section>
<section><b>🚶 08:20–09:10 · Cannaregio → Rialto</b><p>Lista di Spagna · Campo San Geremia · Strada Nova · pontes e canais.</p><small>⏱️ ~35 min de caminhada efetiva; com fotos, reserve ~50 min.</small></section>
<section class="day11-hike"><b>🌉 09:10–09:30 · Ponte di Rialto ⭐⭐⭐</b><p>Atravessar a ponte, observar o Grande Canal dos dois lados e caminhar pelo entorno.</p><small>⭐ Um dos melhores horários para fotos antes do pico de movimento.</small><img src="https://images.unsplash.com/photo-1514890547357-a9ee288728e0?auto=format&fit=crop&w=1400&q=86" alt="Ponte di Rialto" style="width:100%;border-radius:14px;margin-top:12px;max-height:340px;object-fit:cover" loading="lazy"><div class="day4-links"><a href="https://maps.google.com/?q=Ponte+di+Rialto+Venezia" target="_blank" rel="noopener noreferrer">📍 Rialto</a><a href="https://maps.google.com/?q=Mercato+di+Rialto+Venezia" target="_blank" rel="noopener noreferrer">📍 Mercado</a></div></section>
<section><b>🚶 09:30–09:45 · Rialto → San Marco</b><p>Caminhada curta pelas Mercerie e vielas do centro histórico.</p><small>Entre nas ruas laterais quando possível — parte da graça está nos pequenos canais.</small></section>
<section class="day11-hike"><b>⛪ 09:45–10:45 · Basílica de San Marco ⭐⭐⭐</b><p>Visita à <strong>Basílica de São Marcos</strong>. Ideal reservar 09:45 ou 10:00.</p><small>Se quiserem acrescentar algo, priorizem Museu + Loggia dei Cavalli pela vista da praça.</small><img src="https://images.unsplash.com/photo-1533676802871-eca1ae998cd5?auto=format&fit=crop&w=1400&q=86" alt="Piazza San Marco" style="width:100%;border-radius:14px;margin-top:12px;max-height:340px;object-fit:cover" loading="lazy"><div class="day4-links"><a href="https://maps.google.com/?q=Basilica+di+San+Marco+Venezia" target="_blank" rel="noopener noreferrer">📍 Basílica</a><a href="https://tickets.basilicasanmarco.it/" target="_blank" rel="noopener noreferrer">🎟️ Ingresso oficial</a></div></section>
<section><b>🪽 10:45–11:10 · Piazza San Marco</b><p>Torre dell'Orologio · Procuratie · Campanile · Piazzetta · vista para San Giorgio Maggiore.</p><small>Para economizar, não faria a parada para café na própria praça.</small></section>
<section class="day11-hike"><b>👑 11:15–13:00 · Palazzo Ducale</b><p>Salões do governo veneziano · apartamentos · prisões · <strong>Ponte dos Suspiros por dentro</strong>.</p><small>⏱️ 1h30–1h45 é suficiente sem deixar a visita cansativa.</small><img src="https://images.unsplash.com/photo-1545157000-85f257f7b040?auto=format&fit=crop&w=1400&q=86" alt="Palazzo Ducale em Veneza" style="width:100%;border-radius:14px;margin-top:12px;max-height:340px;object-fit:cover" loading="lazy"><div class="day4-links"><a href="https://maps.google.com/?q=Palazzo+Ducale+Venezia" target="_blank" rel="noopener noreferrer">📍 Palazzo Ducale</a><a href="https://palazzoducale.visitmuve.it/" target="_blank" rel="noopener noreferrer">🎟️ Site oficial</a></div></section>
<section><b>📸 13:00–13:20 · Ponte dos Suspiros</b><p>Ver a ponte por fora a partir da <strong>Ponte della Paglia</strong> e caminhar pela Riva degli Schiavoni.</p><a class="day4-map" href="https://maps.google.com/?q=Ponte+della+Paglia+Venezia" target="_blank" rel="noopener noreferrer">📍 Ponte della Paglia</a></section>
<section class="day4-food"><b>🍕 13:30–14:20 · Almoço</b><p>Evitar os restaurantes grudados na Piazza San Marco. Boa ideia: um <strong>bacaro em Castello</strong>.</p><small>💶 ~€10–20 por pessoa · cicchetti, tramezzino, sarde in saor ou baccalà mantecato.</small><a class="day4-map" href="https://maps.google.com/?q=Bacaro+Risorto+Castello+Venezia" target="_blank" rel="noopener noreferrer">📍 Bacaro Risorto</a></section>
<section><b>🍦 14:20–14:40 · Gelato + pausa</b><p>Parada de 15–20 min para gelato e descanso antes da segunda metade do dia.</p><a class="day4-map" href="https://maps.google.com/?q=Gelateria+Gallonetto+Venezia" target="_blank" rel="noopener noreferrer">📍 Gallonetto</a></section>
<section><b>🧭 14:40–15:20 · Castello menos turístico</b><p><strong>Campo Santa Maria Formosa → Libreria Acqua Alta → Campo Santi Giovanni e Paolo.</strong></p><small>❤️ Vielas, pontes pequenas e canais mais tranquilos.</small><img src="https://images.unsplash.com/photo-1534113414509-0eec2bfb493f?auto=format&fit=crop&w=1400&q=86" alt="Canais tranquilos de Veneza" style="width:100%;border-radius:14px;margin-top:12px;max-height:340px;object-fit:cover" loading="lazy"><div class="day4-links"><a href="https://maps.google.com/?q=Libreria+Acqua+Alta+Venezia" target="_blank" rel="noopener noreferrer">📍 Acqua Alta</a><a href="https://maps.google.com/?q=Campo+Santi+Giovanni+e+Paolo+Venezia" target="_blank" rel="noopener noreferrer">📍 Campo</a></div></section>
<section><b>🚶 15:20–16:00 · Travessia até Dorsoduro</b><p>Rialto → Campo San Polo → Frari → Ponte dell'Accademia.</p><small>⏱️ ~35–40 min. Aqui o passeio é a própria cidade.</small></section>
<section class="day4-food"><b>🥂 16:00–16:40 · Cicchetti no Squero</b><p><strong>Cantine del Vino già Schiavi</strong> ou <strong>Osteria Al Squero</strong>.</p><small>💶 ~€5–10 por pessoa. Do outro lado fica o Squero di San Trovaso, tradicional estaleiro de gôndolas.</small><div class="day4-links"><a href="https://maps.google.com/?q=Cantine+del+Vino+gia+Schiavi+Venezia" target="_blank" rel="noopener noreferrer">📍 Schiavi</a><a href="https://maps.google.com/?q=Squero+di+San+Trovaso+Venezia" target="_blank" rel="noopener noreferrer">📍 Squero</a></div></section>
<section><b>🌅 16:40–18:10 · Dorsoduro</b><p>Squero di San Trovaso → Zattere → Punta della Dogana → Santa Maria della Salute → Accademia.</p><small>⭐ A parte mais tranquila do dia, perfeita para desacelerar.</small><img src="https://images.unsplash.com/photo-1558271736-cd043ef2e855?auto=format&fit=crop&w=1400&q=86" alt="Dorsoduro em Veneza" style="width:100%;border-radius:14px;margin-top:12px;max-height:340px;object-fit:cover" loading="lazy"><div class="day4-links"><a href="https://maps.google.com/?q=Zattere+Venezia" target="_blank" rel="noopener noreferrer">📍 Zattere</a><a href="https://maps.google.com/?q=Santa+Maria+della+Salute+Venezia" target="_blank" rel="noopener noreferrer">📍 Salute</a></div></section>
<section class="day4-flight"><b>🌇 18:10–18:35 · Pôr do sol na Accademia</b><p>Chegar à <strong>Ponte dell'Accademia</strong> cerca de 20 minutos antes do pôr do sol.</p><small>📸 Vista clássica do Grande Canal com Santa Maria della Salute.</small><a class="day4-map" href="https://maps.google.com/?q=Ponte+dell+Accademia+Venezia" target="_blank" rel="noopener noreferrer">📍 Accademia</a></section>
<section class="day4-flight"><b>🚤 18:40–19:20 · Grande Canal de vaporetto</b><p>Accademia → <strong>Ferrovia / Santa Lucia</strong> pelo Grande Canal.</p><small>💶 Bilhete unitário ~€9,50. Neste roteiro não compensa o passe de 24 h.</small><div class="day4-links"><a href="https://maps.google.com/?q=Accademia+Vaporetto+Venezia" target="_blank" rel="noopener noreferrer">📍 Vaporetto</a><a href="https://tripplanner.veneziaunica.it/" target="_blank" rel="noopener noreferrer">🚤 Venezia Unica</a></div></section>
<section class="day4-food"><b>🍝 19:30–20:30 · Jantar em Cannaregio</b><p>Jantar numa região menos turística, já perto da rota de retorno a Santa Lucia.</p><small>🍴 Bigoli in salsa, risotto di mare, fritto misto ou baccalà mantecato · ~€15–25 por pessoa.</small><div class="day4-links"><a href="https://maps.google.com/?q=Osteria+Le+Guglie+Venezia" target="_blank" rel="noopener noreferrer">📍 Le Guglie</a><a href="https://maps.google.com/?q=Trattoria+da+Mimmo+Venezia" target="_blank" rel="noopener noreferrer">📍 Da Mimmo</a></div></section>
<section><b>🍨 20:30–20:50 · Último gelato</b><p>Se ainda houver espaço, fechar o dia com gelato em Cannaregio e caminhar até Santa Lucia.</p></section>
<section class="day4-flight"><b>🚆 21:00–22:00 · Retorno</b><p><strong>Venezia Santa Lucia → Venezia Mestre</strong>, pegar o carro e seguir para a hospedagem.</p><small>Meta: começar a sair de Veneza por volta de 21:00–21:30.</small></section>
<section><b>🗺️ Resumo</b><p><strong>07:00</strong> Treviso → Mestre → Santa Lucia → Rialto → San Marco → Palazzo Ducale → almoço → Castello → Dorsoduro → <strong>18:10</strong> pôr do sol → vaporetto → jantar → retorno.</p><small>🟢 Ritmo 7/10 · dia completo, mas com pausas bem distribuídas.</small></section>
</div>`;
 };
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(run,550));else setTimeout(run,550);
})();